atrip::SliceUnion
using atrip::SliceUnion< F >::Tensor = CTF::Tensor<F>
const RankMap<F> atrip::SliceUnion< F >::rankMap
Referenced by atrip::SliceUnion< F >::buildLocalDatabase, atrip::SliceUnion< F >::init, atrip::TAPHH< F >::sliceIntoBuffer, atrip::HHHA< F >::sliceIntoBuffer, atrip::ABPH< F >::sliceIntoBuffer, atrip::ABHH< F >::sliceIntoBuffer, atrip::TABHH< F >::sliceIntoBuffer.
const MPI_Comm atrip::SliceUnion< F >::world
Referenced by atrip::SliceUnion< F >::init.
const MPI_Comm atrip::SliceUnion< F >::universe
Referenced by atrip::SliceUnion< F >::receive, atrip::SliceUnion< F >::send.
const std::vector<size_t> atrip::SliceUnion< F >::sliceLength
Referenced by atrip::SliceUnion< F >::init, atrip::TAPHH< F >::sliceIntoBuffer, atrip::HHHA< F >::sliceIntoBuffer, atrip::ABPH< F >::sliceIntoBuffer, atrip::ABHH< F >::sliceIntoBuffer, atrip::TABHH< F >::sliceIntoBuffer.
const size_t atrip::SliceUnion< F >::sliceSize
Referenced by atrip::SliceUnion< F >::buildLocalDatabase, atrip::SliceUnion< F >::send, atrip::SliceUnion< F >::SliceUnion.
std::vector< std::vector<F> > atrip::SliceUnion< F >::sources
Referenced by atrip::SliceUnion< F >::buildLocalDatabase, atrip::SliceUnion< F >::send, atrip::TAPHH< F >::sliceIntoBuffer, atrip::HHHA< F >::sliceIntoBuffer, atrip::ABPH< F >::sliceIntoBuffer, atrip::ABHH< F >::sliceIntoBuffer, atrip::TABHH< F >::sliceIntoBuffer, atrip::SliceUnion< F >::SliceUnion.
std::vector< Slice<F> > atrip::SliceUnion< F >::slices
Referenced by atrip::SliceUnion< F >::buildLocalDatabase, atrip::SliceUnion< F >::checkForDuplicates, atrip::SliceUnion< F >::clearUnusedSlicesForNext, atrip::SliceUnion< F >::receive, atrip::SliceUnion< F >::SliceUnion, atrip::SliceUnion< F >::unwrapSlice.
Slice<F>::Name atrip::SliceUnion< F >::name
Referenced by atrip::SliceUnion< F >::buildLocalDatabase, atrip::SliceUnion< F >::clearUnusedSlicesForNext, atrip::SliceUnion< F >::SliceUnion, atrip::SliceUnion< F >::unwrapSlice.
const std::vector<typename Slice<F>::Type> atrip::SliceUnion< F >::sliceTypes
Referenced by atrip::SliceUnion< F >::neededSlices, atrip::SliceUnion< F >::SliceUnion, atrip::SliceUnion< F >::unwrapAll.
std::vector< DataPtr<F> > atrip::SliceUnion< F >::sliceBuffers
Referenced by atrip::SliceUnion< F >::SliceUnion, atrip::SliceUnion< F >::~SliceUnion.
std::set< DataPtr<F> > atrip::SliceUnion< F >::freePointers
Referenced by atrip::SliceUnion< F >::buildLocalDatabase, atrip::SliceUnion< F >::clearUnusedSlicesForNext, atrip::SliceUnion< F >::SliceUnion.
virtual void atrip::SliceUnion< F >::sliceIntoBuffer(size_t iteration, Tensor &to, Tensor const &from)=0
Referenced by atrip::SliceUnion< F >::init.
void atrip::SliceUnion< F >::checkForDuplicates() const
References atrip::SliceUnion< F >::slices.
std::vector< typename Slice< F >::Ty_x_Tu > atrip::SliceUnion< F >::neededSlices(ABCTuple const &abc)
References atrip::SliceUnion< F >::sliceTypes.
Referenced by atrip::SliceUnion< F >::buildLocalDatabase, atrip::SliceUnion< F >::clearUnusedSlicesForNext.
Slice< F >::LocalDatabase atrip::SliceUnion< F >::buildLocalDatabase(ABCTuple const &abc)
References _CHECK_CUDA_SUCCESS, atrip::Slice< F >::data, atrip::Slice< F >::findOneByType, atrip::SliceUnion< F >::freePointers, atrip::Slice< F >::Info::from, atrip::Slice< F >::info, atrip::SliceUnion< F >::name, atrip::SliceUnion< F >::neededSlices, atrip::pretty_print, atrip::Atrip::rank, atrip::SliceUnion< F >::rankMap, atrip::SliceUnion< F >::slices, atrip::SliceUnion< F >::sliceSize, atrip::SliceUnion< F >::sources, SOURCES_DATA, WITH_CHRONO, WITH_RANK.
void atrip::SliceUnion< F >::clearUnusedSlicesForNext(ABCTuple const &abc)
References atrip::Slice< F >::data, atrip::Slice< F >::free, atrip::SliceUnion< F >::freePointers, atrip::Slice< F >::hasRecycledReferencingToIt, atrip::Slice< F >::info, atrip::Slice< F >::markReady, atrip::SliceUnion< F >::name, atrip::SliceUnion< F >::neededSlices, atrip::pretty_print, atrip::SliceUnion< F >::slices, atrip::Slice< F >::Info::state, atrip::Slice< F >::Info::type, WITH_OCD, WITH_RANK.
atrip::SliceUnion< F >::SliceUnion(std::vector< typename Slice< F >::Type > sliceTypes_, std::vector< size_t > sliceLength_, std::vector< size_t > paramLength, size_t np, MPI_Comm child_world, MPI_Comm global_world, typename Slice< F >::Name name_, size_t nSliceBuffers=4)
References atrip::SliceUnion< F >::freePointers, LOG, atrip::SliceUnion< F >::name, atrip::SliceUnion< F >::sliceBuffers, atrip::SliceUnion< F >::slices, atrip::SliceUnion< F >::sliceSize, atrip::SliceUnion< F >::sliceTypes, atrip::SliceUnion< F >::sources, WITH_RANK.
void atrip::SliceUnion< F >::init(Tensor const &sourceTensor)
References atrip::Atrip::rank, atrip::SliceUnion< F >::rankMap, atrip::SliceUnion< F >::sliceIntoBuffer, atrip::SliceUnion< F >::sliceLength, WITH_OCD, WITH_RANK, atrip::SliceUnion< F >::world.
void atrip::SliceUnion< F >::send(size_t otherRank, typename Slice< F >::LocalDatabaseElement const &el, size_t tag) const noexcept
Send asynchronously only if the state is Fetch.
References atrip::SliceUnion< F >::sliceSize, atrip::SliceUnion< F >::sources, SOURCES_DATA, atrip::SliceUnion< F >::universe, WITH_CRAZY_DEBUG, WITH_RANK.
void atrip::SliceUnion< F >::receive(typename Slice< F >::Info const &info, size_t tag) noexcept
Receive asynchronously only if the state is Fetch.
References atrip::Slice< F >::findByInfo, atrip::Atrip::rank, atrip::SliceUnion< F >::slices, atrip::SliceUnion< F >::universe.
void atrip::SliceUnion< F >::unwrapAll(ABCTuple const &abc)
References atrip::SliceUnion< F >::sliceTypes, atrip::SliceUnion< F >::unwrapSlice.
Referenced by atrip::Atrip::run.
DataPtr< F > atrip::SliceUnion< F >::unwrapSlice(typename Slice< F >::Type type, ABCTuple const &abc)
References atrip::Slice< F >::findByTypeAbc, atrip::SliceUnion< F >::name, atrip::pretty_print, atrip::SliceUnion< F >::slices, atrip::SliceUnion< F >::unwrapSlice, WITH_CRAZY_DEBUG, WITH_RANK.
Referenced by atrip::Atrip::run, atrip::SliceUnion< F >::unwrapAll, atrip::SliceUnion< F >::unwrapSlice.
atrip::SliceUnion< F >::~SliceUnion()
References atrip::SliceUnion< F >::sliceBuffers.