atrip::group_and_sort
size_t atrip::group_and_sort::isOnNode(size_t tuple, size_t nNodes)
Referenced by getTupleNodes, specialDistribution.
std::vector< size_t > atrip::group_and_sort::getTupleNodes(ABCTuple const &t, size_t nNodes)
References isOnNode, atrip::unique.
Referenced by specialDistribution.
ABCTuples atrip::group_and_sort::specialDistribution(Info const &info, ABCTuples const &allTuples)
References getTupleNodes, atrip::INVALID_TUPLE, isOnNode, atrip::group_and_sort::Info::nNodes, atrip::group_and_sort::Info::nodeId, WITH_DBG.
Referenced by main.
std::vector< ABCTuple > atrip::group_and_sort::main(MPI_Comm universe, size_t Nv)
References atrip::FAKE_TUPLE, atrip::getAllTuplesList, atrip::getNodeInfos, atrip::getNodeNames, LOG, atrip::group_and_sort::Info::nodeId, specialDistribution, atrip::unique.
Referenced by atrip::group_and_sort::Distribution::getTuples.