atrip
reordering_t
using atrip::Complex = typedef std::complex<double>
using atrip::IterationDescriptor = typedef std::function<void(IterationDescription const&)>
typedef std::array< size_t, 3 > atrip::ABCTuple
typedef std::array< size_t, 2 > atrip::PartialTuple
typedef std::vector< ABCTuple > atrip::ABCTuples
using atrip::DataPtr = typedef F*
using atrip::DataFieldType = typedef typename DataField<F>::type
using atrip::Timings = typedef std::map<std::string, Timer>
size_t const atrip::No
Referenced by doublesContribution, for, getEnergySame, atrip::Atrip::run, singlesContribution, atrip::TAPHH< F >::sliceIntoBuffer, atrip::HHHA< F >::sliceIntoBuffer, atrip::ABPH< F >::sliceIntoBuffer, atrip::ABHH< F >::sliceIntoBuffer, atrip::TABHH< F >::sliceIntoBuffer.
size_t const F* const atrip::epsi
Referenced by for, getEnergySame, atrip::Atrip::run.
size_t const F* const F* const atrip::Tijk
Referenced by doublesContribution, for, getEnergySame, atrip::Atrip::run.
size_t const F* const F* const F* const atrip::Zijk
Referenced by for, getEnergySame, atrip::Atrip::run.
constexpr ABCTuple atrip::FAKE_TUPLE
Referenced by getTuplesList, atrip::group_and_sort::main, atrip::TuplesDistribution::tupleIsFake.
constexpr ABCTuple atrip::INVALID_TUPLE
Referenced by atrip::group_and_sort::specialDistribution.
void atrip::xgemm< double >(const char *transa, const char *transb, const int *m, const int *n, const int *k, double *alpha, const typename DataField< double >::type *A, const int *lda, const typename DataField< double >::type *B, const int *ldb, double *beta, typename DataField< double >::type *C, const int *ldc)
References dgemm_, atrip::Atrip::rank.
void atrip::xgemm< Complex >(const char *transa, const char *transb, const int *m, const int *n, const int *k, Complex *alpha, const typename DataField< Complex >::type *A, const int *lda, const typename DataField< Complex >::type *B, const int *ldb, Complex *beta, typename DataField< Complex >::type *C, const int *ldc)
References _CHECK_CUBLAS_SUCCESS, zgemm_.
void atrip::xcopy< double >(int *n, const DataFieldType< double > *x, int *incx, DataFieldType< double > *y, int *incy)
References dcopy_.
void atrip::xcopy< Complex >(int *n, const DataFieldType< Complex > *x, int *incx, DataFieldType< Complex > *y, int *incy)
References zcopy_.
double atrip::maybeConjugate(const double a)
Complex atrip::maybeConjugate(const Complex a)
__MAYBE_GLOBAL__ void atrip::reorder(reorder_proxy< F, R > proxy, size_t size, F *to, F *from)
atrip::_MAKE_REORDER_(IJK, GO(to[idx], from[_IJK_(i, j, k)])) _MAKE_REORDER_(IKJ
atrip::GO(to[idx], from[_IJK_(i, k, j)])) _MAKE_REORDER_(JIK
Referenced by singlesContribution.
atrip::GO(to[idx], from[_IJK_(j, i, k)])) _MAKE_REORDER_(JKI
atrip::GO(to[idx], from[_IJK_(j, k, i)])) _MAKE_REORDER_(KIJ
atrip::GO(to[idx], from[_IJK_(k, i, j)])) _MAKE_REORDER_(KJI
atrip::GO(to[idx], from[_IJK_(k, j, i)])) template< typename F > double getEnergyDistinct(F const epsabc
F atrip::energy(0.)
Referenced by for, getEnergySame, atrip::Atrip::run.
atrip::for(size_t kk=0;kk< No;kk+=blockSize)
References energy, epsi, No, Tijk, Zijk.
double atrip::getEnergySame(F const epsabc, size_t const No, F *const epsi, F *const Tijk, F *const Zijk)
References energy, epsi, No, Tijk, Zijk.
template double atrip::getEnergyDistinct(double const epsabc, size_t const No, double *const epsi, double *const Tijk, double *const Zijk)
template double atrip::getEnergySame(double const epsabc, size_t const No, double *const epsi, double *const Tijk, double *const Zijk)
template double atrip::getEnergyDistinct(Complex const epsabc, size_t const No, Complex *const epsi, Complex *const Tijk, Complex *const Zijk)
template double atrip::getEnergySame(Complex const epsabc, size_t const No, Complex *const epsi, Complex *const Tijk, Complex *const Zijk)
__MAYBE_GLOBAL__ void atrip::singlesContribution(size_t No, size_t Nv, size_t a, size_t b, size_t c, DataFieldType< F > *const Tph, DataFieldType< F > *const VABij, DataFieldType< F > *const VACij, DataFieldType< F > *const VBCij, DataFieldType< F > *Zijk)
References GO, No.
template __MAYBE_GLOBAL__ void atrip::singlesContribution< double >(size_t No, size_t Nv, size_t a, size_t b, size_t c, double *const Tph, double *const VABij, double *const VACij, double *const VBCij, double *Zijk)
template __MAYBE_GLOBAL__ void atrip::singlesContribution< Complex >(size_t No, size_t Nv, size_t a, size_t b, size_t c, DataFieldType< Complex > *const Tph, DataFieldType< Complex > *const VABij, DataFieldType< Complex > *const VACij, DataFieldType< Complex > *const VBCij, DataFieldType< Complex > *Zijk)
void atrip::doublesContribution(const ABCTuple &abc, size_t const No, size_t const Nv, DataPtr< F > const VABph, DataPtr< F > const VACph, DataPtr< F > const VBCph, DataPtr< F > const VBAph, DataPtr< F > const VCAph, DataPtr< F > const VCBph, DataPtr< F > const VhhhA, DataPtr< F > const VhhhB, DataPtr< F > const VhhhC, DataPtr< F > const TAphh, DataPtr< F > const TBphh, DataPtr< F > const TCphh, DataPtr< F > const TABhh, DataPtr< F > const TAChh, DataPtr< F > const TBChh, DataFieldType< F > *Tijk_)
References _CHECK_CUDA_SUCCESS, No, Tijk, WITH_CHRONO.
template void atrip::doublesContribution< double >(const ABCTuple &abc, size_t const No, size_t const Nv, DataPtr< double > const VABph, DataPtr< double > const VACph, DataPtr< double > const VBCph, DataPtr< double > const VBAph, DataPtr< double > const VCAph, DataPtr< double > const VCBph, DataPtr< double > const VhhhA, DataPtr< double > const VhhhB, DataPtr< double > const VhhhC, DataPtr< double > const TAphh, DataPtr< double > const TBphh, DataPtr< double > const TCphh, DataPtr< double > const TABhh, DataPtr< double > const TAChh, DataPtr< double > const TBChh, DataFieldType< double > *Tijk)
template void atrip::doublesContribution< Complex >(const ABCTuple &abc, size_t const No, size_t const Nv, DataPtr< Complex > const VABph, DataPtr< Complex > const VACph, DataPtr< Complex > const VBCph, DataPtr< Complex > const VBAph, DataPtr< Complex > const VCAph, DataPtr< Complex > const VCBph, DataPtr< Complex > const VhhhA, DataPtr< Complex > const VhhhB, DataPtr< Complex > const VhhhC, DataPtr< Complex > const TAphh, DataPtr< Complex > const TBphh, DataPtr< Complex > const TCphh, DataPtr< Complex > const TABhh, DataPtr< Complex > const TAChh, DataPtr< Complex > const TBChh, DataFieldType< Complex > *Tijk)
void atrip::dgemm_(const char *transa, const char *transb, const int *m, const int *n, const int *k, double *alpha, const double *a, const int *lda, const double *b, const int *ldb, double *beta, double *c, const int *ldc)
Referenced by xgemm< double >.
void atrip::zgemm_(const char *transa, const char *transb, const int *m, const int *n, const int *k, Complex *alpha, const Complex *A, const int *lda, const Complex *B, const int *ldb, Complex *beta, Complex *C, const int *ldc)
Referenced by xgemm< Complex >.
void atrip::dcopy_(int *n, const double *x, int *incx, double *y, int *incy)
Referenced by xcopy< double >.
void atrip::zcopy_(int *n, const void *x, int *incx, void *y, int *incy)
Referenced by xcopy< Complex >.
void atrip::xcopy(int *n, const DataFieldType< F > *x, int *incx, DataFieldType< F > *y, int *incy)
void atrip::xgemm(const char *transa, const char *transb, const int *m, const int *n, const int *k, F *alpha, const DataFieldType< F > *A, const int *lda, const DataFieldType< F > *B, const int *ldb, F *beta, DataFieldType< F > *C, const int *ldc)
void atrip::write_checkpoint(Checkpoint const &c, std::string const &filepath)
References atrip::Checkpoint::energy, atrip::Checkpoint::iteration, atrip::Checkpoint::nnodes, atrip::Checkpoint::no, atrip::Checkpoint::nranks, atrip::Checkpoint::nv, atrip::Checkpoint::rankRoundRobin.
Referenced by atrip::Atrip::run.
Checkpoint atrip::read_checkpoint(std::ifstream &in)
References atrip::Checkpoint::energy, atrip::Checkpoint::iteration, atrip::Checkpoint::nnodes, atrip::Checkpoint::no, atrip::Checkpoint::nranks, atrip::Checkpoint::nv, atrip::Checkpoint::rankRoundRobin.
Referenced by read_checkpoint, atrip::Atrip::run.
Checkpoint atrip::read_checkpoint(std::string const &filepath)
References read_checkpoint.
F atrip::maybeConjugate(const F)
void atrip::registerIterationDescriptor(IterationDescriptor)
double atrip::getEnergyDistinct(F const epsabc, size_t const No, F *const epsi, F *const Tijk, F *const Zijk)
void atrip::singlesContribution(size_t No, size_t Nv, size_t a, size_t b, size_t c, DataFieldType< F > *const Tph, DataFieldType< F > *const VABij, DataFieldType< F > *const VACij, DataFieldType< F > *const VBCij, DataFieldType< F > *Zijk)
References GO, No.
std::ostream & atrip::operator<<(std::ostream &out, typename Slice< F >::Location const &v)
std::ostream & atrip::operator<<(std::ostream &out, typename Slice< F >::Info const &i)
SliceUnion< F > & atrip::unionByName(std::vector< SliceUnion< F > * > const &unions, typename Slice< F >::Name name)
Referenced by atrip::Atrip::run.
std::vector< std::string > atrip::getNodeNames(MPI_Comm comm)
Referenced by getClusterInfo, atrip::group_and_sort::main.
A atrip::unique(A const &xs)
References unique.
Referenced by getClusterInfo, getNodeInfos, atrip::group_and_sort::getTupleNodes, atrip::group_and_sort::main, unique.
std::vector< RankInfo > atrip::getNodeInfos(std::vector< string > const &nodeNames)
References unique.
Referenced by getClusterInfo, atrip::group_and_sort::main.
ClusterInfo atrip::getClusterInfo(MPI_Comm comm)
References getNodeInfos, getNodeNames, unique.
Referenced by atrip::Atrip::run.
ABCTuples atrip::getTuplesList(size_t Nv, size_t rank, size_t np)
References FAKE_TUPLE, LOG, WITH_RANK.
Referenced by atrip::NaiveDistribution::getTuples.
ABCTuples atrip::getAllTuplesList(const size_t Nv)
Referenced by atrip::group_and_sort::main.
void atrip::sliceIntoVector(std::vector< F > &v, CTF::Tensor< F > &toSlice, std::vector< int64_t > const low, std::vector< int64_t > const up, CTF::Tensor< F > const &origin, std::vector< int64_t > const originLow, std::vector< int64_t > const originUp)
References pretty_print, WITH_OCD, WITH_RANK.
std::string atrip::pretty_print(T &&value)
References pretty_print.
Referenced by atrip::SliceUnion< F >::buildLocalDatabase, atrip::SliceUnion< F >::clearUnusedSlicesForNext, atrip::Slice< F >::findByInfo, atrip::Slice< F >::findByTypeAbc, atrip::Slice< F >::findRecycledSource, pretty_print, atrip::Atrip::run, sliceIntoVector, atrip::SliceUnion< F >::unwrapSlice.