atrip::Slice::mpi
static MPI_Datatype atrip::Slice< F >::mpi::vector(size_t n, MPI_Datatype const &DT)
Referenced by atrip::Slice< F >::mpi::localDatabaseElement, atrip::Slice< F >::mpi::sliceInfo.
static MPI_Datatype atrip::Slice< F >::mpi::sliceLocation()
References atrip::Slice< F >::Location::rank, atrip::Slice< F >::Location::source, atrip::Slice< F >::mpi::usizeDt.
Referenced by atrip::Slice< F >::mpi::sliceInfo.
static MPI_Datatype atrip::Slice< F >::mpi::usizeDt()
Referenced by atrip::Slice< F >::mpi::sliceInfo, atrip::Slice< F >::mpi::sliceLocation.
static MPI_Datatype atrip::Slice< F >::mpi::sliceInfo()
References atrip::Slice< F >::Info::from, atrip::Slice< F >::Info::recycling, atrip::Slice< F >::mpi::sliceLocation, atrip::Slice< F >::Info::state, atrip::Slice< F >::Info::tuple, atrip::Slice< F >::Info::type, atrip::Slice< F >::mpi::usizeDt, atrip::Slice< F >::mpi::vector.
Referenced by atrip::Slice< F >::mpi::localDatabaseElement.
static MPI_Datatype atrip::Slice< F >::mpi::localDatabaseElement()
References atrip::Slice< F >::LocalDatabaseElement::info, atrip::Slice< F >::LocalDatabaseElement::name, atrip::Slice< F >::mpi::sliceInfo, atrip::Slice< F >::mpi::vector.