atrip::Slice
Type
State
Name
using atrip::Slice< F >::Ty_x_Tu = std::pair< Type, PartialTuple >
using atrip::Slice< F >::LocalDatabase = std::vector<LocalDatabaseElement>
using atrip::Slice< F >::Database = LocalDatabase
Info atrip::Slice< F >::info
Referenced by atrip::SliceUnion< F >::buildLocalDatabase, atrip::SliceUnion< F >::clearUnusedSlicesForNext, atrip::Slice< F >::findByInfo, atrip::Slice< F >::findRecycledSource, atrip::Slice< F >::free, atrip::Slice< F >::hasRecycledReferencingToIt, atrip::Slice< F >::hasValidDataPointer, atrip::Slice< F >::isDirectlyFetchable, atrip::Slice< F >::isFree, atrip::Slice< F >::isRecyclable, atrip::Slice< F >::isUnwrappable, atrip::Slice< F >::isUnwrapped, atrip::Slice< F >::markReady, atrip::Slice< F >::unwrapAndMarkReady.
DataPtr<F> atrip::Slice< F >::data
Referenced by atrip::SliceUnion< F >::buildLocalDatabase, atrip::SliceUnion< F >::clearUnusedSlicesForNext, atrip::Slice< F >::free, atrip::Slice< F >::hasValidDataPointer, atrip::Slice< F >::isFree, atrip::Slice< F >::unwrapAndMarkReady.
MPI_Request atrip::Slice< F >::request
Referenced by atrip::Slice< F >::unwrapAndMarkReady.
const size_t atrip::Slice< F >::size
Referenced by atrip::Slice< F >::unwrapAndMarkReady.
static PartialTuple atrip::Slice< F >::subtupleBySlice(ABCTuple abc, Type sliceType)
References atrip::Slice< F >::A, atrip::Slice< F >::AB, atrip::Slice< F >::AC, atrip::Slice< F >::B, atrip::Slice< F >::BA, atrip::Slice< F >::BC, atrip::Slice< F >::C, atrip::Slice< F >::CA, atrip::Slice< F >::CB.
Referenced by atrip::RankMap< F >::find, atrip::Slice< F >::findByTypeAbc, atrip::Atrip::run.
static std::vector< Slice< F > * > atrip::Slice< F >::hasRecycledReferencingToIt(std::vector< Slice< F > > &slices, Info const &info)
References atrip::Slice< F >::info, atrip::Slice< F >::Recycled, atrip::Slice< F >::Info::tuple, atrip::Slice< F >::Info::type.
Referenced by atrip::SliceUnion< F >::clearUnusedSlicesForNext.
static Slice< F > & atrip::Slice< F >::findOneByType(std::vector< Slice< F > > &slices, Slice< F >::Type type)
References WITH_CRAZY_DEBUG, WITH_RANK.
Referenced by atrip::SliceUnion< F >::buildLocalDatabase.
static Slice< F > & atrip::Slice< F >::findRecycledSource(std::vector< Slice< F > > &slices, Slice< F >::Info info)
References atrip::Slice< F >::info, atrip::pretty_print, atrip::Atrip::rank, WITH_CRAZY_DEBUG, WITH_RANK.
static Slice< F > & atrip::Slice< F >::findByTypeAbc(std::vector< Slice< F > > &slices, Slice< F >::Type type, ABCTuple const &abc)
References atrip::pretty_print, atrip::Atrip::rank, atrip::Slice< F >::subtupleBySlice, WITH_CRAZY_DEBUG, WITH_RANK.
Referenced by atrip::SliceUnion< F >::unwrapSlice.
static Slice< F > & atrip::Slice< F >::findByInfo(std::vector< Slice< F > > &slices, Slice< F >::Info const &info)
References atrip::Slice< F >::info, atrip::pretty_print, WITH_CRAZY_DEBUG, WITH_RANK.
Referenced by atrip::SliceUnion< F >::receive.
void atrip::Slice< F >::markReady() noexcept
References atrip::Slice< F >::Blank, atrip::Slice< F >::info, atrip::Slice< F >::Ready, atrip::Slice< F >::Info::recycling, atrip::Slice< F >::Info::state.
Referenced by atrip::SliceUnion< F >::clearUnusedSlicesForNext, atrip::Slice< F >::unwrapAndMarkReady.
bool atrip::Slice< F >::isUnwrapped() const noexcept
References atrip::Slice< F >::info, atrip::Slice< F >::Ready, atrip::Slice< F >::SelfSufficient, atrip::Slice< F >::Info::state.
Referenced by atrip::Slice< F >::isUnwrappable.
bool atrip::Slice< F >::isUnwrappable() const noexcept
References atrip::Slice< F >::Dispatched, atrip::Slice< F >::info, atrip::Slice< F >::isUnwrapped, atrip::Slice< F >::Recycled, atrip::Slice< F >::Info::state.
bool atrip::Slice< F >::isDirectlyFetchable() const noexcept
References atrip::Slice< F >::Dispatched, atrip::Slice< F >::info, atrip::Slice< F >::Ready, atrip::Slice< F >::Info::state.
void atrip::Slice< F >::free() noexcept
References atrip::Slice< F >::Acceptor, atrip::Slice< F >::Blank, atrip::Slice< F >::data, DataNullPtr, atrip::Slice< F >::Info::from, atrip::Slice< F >::info, atrip::Slice< F >::Info::recycling, atrip::Slice< F >::Info::state, atrip::Slice< F >::Info::tuple, atrip::Slice< F >::Info::type.
Referenced by atrip::SliceUnion< F >::clearUnusedSlicesForNext.
bool atrip::Slice< F >::isFree() const noexcept
References atrip::Slice< F >::Acceptor, atrip::Slice< F >::Blank, atrip::Slice< F >::data, DataNullPtr, atrip::Slice< F >::Info::from, atrip::Slice< F >::info, atrip::Slice< F >::Location::rank, atrip::Slice< F >::Info::recycling, atrip::Slice< F >::Location::source, atrip::Slice< F >::Info::state, atrip::Slice< F >::Info::tuple, atrip::Slice< F >::Info::type.
bool atrip::Slice< F >::isRecyclable() const noexcept
References atrip::Slice< F >::Dispatched, atrip::Slice< F >::Fetch, atrip::Slice< F >::hasValidDataPointer, atrip::Slice< F >::info, atrip::Slice< F >::Ready, atrip::Slice< F >::Info::state.
bool atrip::Slice< F >::hasValidDataPointer() const noexcept
References atrip::Slice< F >::Acceptor, atrip::Slice< F >::Blank, atrip::Slice< F >::data, DataNullPtr, atrip::Slice< F >::info, atrip::Slice< F >::Info::state, atrip::Slice< F >::Info::type.
Referenced by atrip::Slice< F >::isRecyclable.
void atrip::Slice< F >::unwrapAndMarkReady()
References _CHECK_CUDA_SUCCESS, atrip::Slice< F >::data, atrip::Slice< F >::Dispatched, atrip::Slice< F >::info, atrip::Slice< F >::markReady, atrip::Slice< F >::Ready, atrip::Slice< F >::request, atrip::Slice< F >::size, atrip::Slice< F >::Info::state, WITH_CHRONO, WITH_RANK.
atrip::Slice< F >::Slice(size_t size_)