atrip::RankMap
template bool RankMap::RANK_ROUND_ROBIN
Referenced by atrip::RankMap< double >::find.
std::vector<size_t> const atrip::RankMap< F >::lengths
Referenced by atrip::RankMap< double >::RankMap, atrip::RankMap< double >::find.
size_t const atrip::RankMap< F >::np
Referenced by atrip::RankMap< double >::find, atrip::RankMap< double >::nSources, atrip::RankMap< double >::isPaddingRank.
size_t const atrip::RankMap< F >::size
Referenced by atrip::RankMap< double >::nSources, atrip::RankMap< double >::isPaddingRank.
ClusterInfo const atrip::RankMap< F >::clusterInfo
Referenced by atrip::RankMap< double >::find.
atrip::RankMap< F >::RankMap(std::vector< size_t > lens, size_t np_, MPI_Comm comm)
size_t atrip::RankMap< F >::find(typename Slice< F >::Location const &p) const noexcept
Referenced by atrip::TAPHH< F >::sliceIntoBuffer, atrip::HHHA< F >::sliceIntoBuffer, atrip::ABPH< F >::sliceIntoBuffer, atrip::ABHH< F >::sliceIntoBuffer, atrip::TABHH< F >::sliceIntoBuffer.
size_t atrip::RankMap< F >::nSources() const noexcept
Referenced by atrip::RankMap< double >::isSourcePadding.
bool atrip::RankMap< F >::isPaddingRank(size_t rank) const noexcept
Referenced by atrip::RankMap< double >::isSourcePadding.
bool atrip::RankMap< F >::isSourcePadding(size_t rank, size_t source) const noexcept
Slice<F>::Location atrip::RankMap< F >::find(ABCTuple const &abc, typename Slice< F >::Type sliceType) const